#!/bin/bash
# This is an optional hook for defining paths normally set by default in
# /usr/lib/systemd/scripts/ioc.sh

export PSPKG_ROOT=/reg/common/package
export PYPS_ROOT=/reg/g/pcds/pyps
export IOC_ROOT=/reg/g/pcds/package/epics/3.14/ioc
export CAMRECORD_ROOT=/reg/g/pcds/controls/camrecord
export IOC_DATA=/reg/d/iocData
export IOC_COMMON=/reg/d/iocCommon
